# -*- coding: utf-8 -*-
"""Q5_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XvKjwPh4nrJKzEwAChcZ2elK-elXdrBO
"""

import numpy as np
import pandas as pd
import math

map = pd.read_csv('/content/drive/My Drive/Probs Stats/q5.csv', header = None)

def  MAP_descision(w, p):
  mu = 0.5
  sigma_square = 1
  result = []
  const = -math.log((1-p)/p) * (sigma_square/(2 * mu))
  if np.sum(w) <= const:
    return 0
  else:
    return 1

p = [0.1, 0.3, 0.5, 0.8]
for i in range(len(p)):
  result = []
  for j in range(map.shape[1]):
    w = map.iloc[:, j]
    result.append(str(MAP_descision(w, p[i])))
  print('For 𝑃(H0) = ' + str(p[i]) + ', the hypotheses selected are ::', result)